version: '2'
services:
    ionic2sample-app:
        image: ionic2sample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ionic2sample-mysql:3306/ionic2sample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ionic2sample-mysql:
        extends:
            file: mysql.yml
            service: ionic2sample-mysql
